before_script:
  - export DISPLAY=:10
  - Xvfb :10 -screen 0 1366x768x24 -ac +extension RANDR &
  - npm update
  - grunt
  
.artifact_template: &artifacts_template
  artifacts:
    name: "%CI_BUILD_NAME%_%CI_BUILD_REF_NAME%"
    when: always
    paths:
    - '"%CI_PROJECT_DIR%/build/artifacts"'

chrome_test:
    image: thib3113/selenium-chrome-headless:latest
    dependencies: []
    <<: *artifacts_template
    script:
        - google-chrome --remote-debugging-port=9222 --load-extension=./build/Chrome --no-first-run &
        - nohup java -jar /usr/local/bin/selenium-server.jar &
        - ./node_modules/.bin/codeceptjs run
    tags:
        - docker
        - linux
        - selenium