before_script:
  - export DISPLAY=:10
  - Xvfb :10 -screen 0 1366x768x24 -ac &
  - wget https://deb.nodesource.com/setup_7.x -v -O install.sh && ./install.sh
  - apt-get install -y build-essential nodejs
  - npm install -g grunt
  - npm update
  - grunt
  
chrome_test:
    image: thib3113/selenium-chrome-headless
    script:
        - google-chrome --remote-debugging-port=9222 --load-extension=./build/Chrome --no-first-run &
        - nohup java -jar /usr/local/bin/selenium-server.jar &
        - ./vendor/.bin/codecept run